# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pup-aarch64-linux = {
    pname = "pup-aarch64-linux";
    version = "0.65.4";
    src = fetchTarball {
      url = "https://github.com/DataDog/pup/releases/download/v0.65.4/pup_0.65.4_Linux_arm64.tar.gz";
      sha256 = "sha256-ZeFKw2avqnYbU3YY94RJQOCnUmu2GA8vLybc9Exk6HY=";
    };
  };
  pup-x86_64-linux = {
    pname = "pup-x86_64-linux";
    version = "0.65.4";
    src = fetchTarball {
      url = "https://github.com/DataDog/pup/releases/download/v0.65.4/pup_0.65.4_Linux_x86_64.tar.gz";
      sha256 = "sha256-EVnPuFJP+dT7RdCvelQcHCgaqKyubqyGGaFXxgeNleo=";
    };
  };
}
