nerdfont: true
agent: claude

# disable automatic tmux format modification
status_format: false

panes:
  - command: <agent> 
  - split: horizontal
    focus: true

sandbox:
  enabled: true
  container:
    runtime: docker
