# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'niksingh710/minimal-tmux-status'

# mouse mode
set -g mouse on
# vi mode
set -g mode-keys vi
set -g status-keys vi

# split-window in cwd
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# sesh
bind C-o display-popup -E "sesh connect $(sesh list | fzf)"
bind C-s display-popup -E "sesh connect $(sesh list -t | fzf)"
bind C-k confirm -p "Kill current session? (y/N):" "run-shell 'sesh last && tmux kill-session -t #S'"

# workmux
bind C-t run-shell "workmux sidebar -s"
set -g @minimal-tmux-window-status-format " #I:#W#{?@workmux_status, #{@workmux_status},} "

# tpm
set-environment -g PATH "/opt/homebrew/bin:$PATH"
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
