#!/usr/bin/env sh
mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}

if [ -d "$1" ]; then
    eza -hl --color=always "$1"
elif [ "$category" = text ]; then
    bat --color=always "$1" --plain
else
    lesspipe.sh "$1" | bat --color=always --plain
fi
